name: teleportr unit tests

on:
  push:
    paths:
      - 'go/teleportr/**'
    branches:
      - 'master'
      - 'develop'
      - '*rc'
      - 'release/*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

defaults:
  run:
    working-directory: './go/teleportr'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...
